import shuffle from './utils/shuffle';

const questions = [
  'What is your startup going to do?',
  'Who are your potential Users? Who needs what you’re making?',
  'What obstacles are in your path and how do you overcome them?',
  'What’s wrong with existing options?',
  'How you’ll overcome the barriers that allow existing options to stay bad?',
  'How do you know they the users need it?',
  'What are the developers and designers doing now?',
  'What makes you different from existing options?',
  'Why isn’t someone already doing this?',
  'How will customers/users find out about you?',
  'What resistance will they have to try you?',
  'How will you overcome that resistance?',
  'What are the key things about your field that outsiders don’t understand?',
  'Who are your paying customers?',
  'If your startup succeeds, what additional areas might you be able to expand into?',
  'What have you learned so far from working on it?',
  'Six months from now, what’s going to be your biggest problem?',
  'Have you raised funding?',
  'What makes new users try you?',
  'What competition do you fear most?',
  'Will you reincorporate as a US company?',
  'What’s an impressive thing you have done?',
  'Where is rocket science here?',
  'Why did you pick this idea to work on?',
  'Who would you hire or how would you add to your team?',
  'Who is “the boss”?',
  'What is the next step with product evolution?',
  'How does your product work in more detail?',
  'What do you understand that others don’t?',
  'Where do new users come from?',
  'How big an opportunity is there?',
  'What’s new about what you make?',
  'How many users do you have?',
  'Why isn’t someone already doing this?',
  'What are the top things users want?',
  'What is your burn rate?',
  'What is your churn?',
  'What domain expertise do you have?',
  'What’s the conversion rate?',
  'What systems have you hacked?',
  'Why did your team get together?',
  'In what ways are you resourceful?',
  'What has surprised you about user behavior?',
  'What is your user growth rate?',
  'Would you relocate to Silicon Valley?',
  'How long can you go before funding?',
  'How will you make money?',
  'Will your team stick at this?',
  'How much does customer acquisition cost?',
  'Who in your team does what?',
  'How are you meeting customers?',
  'How many users are paying?',
  'What is your growth like?',
  'What’s the worst thing that has happened?',
  'What’s the biggest mistake you have made?',
];

export default shuffle(questions);
